name: text_to_speech
description: A Flutter plugin provides TTS (Text-To-Speech) Service.
version: 0.1.0
homepage: https://github.com/ixsans/text_to_speech

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.ixsans.text_to_speech
        pluginClass: TextToSpeechPlugin
      ios:
        pluginClass: TextToSpeechPlugin
      web:
        pluginClass: TextToSpeechWeb
        fileName: text_to_speech_web.dart
      macos:
        pluginClass: TextToSpeechPlugin

  assets:
    - packages/text_to_speech/assets/locales.json
